import * as core from "@actions/core";
import type { CreateDocsPRParams, DocUpdate, SourcePR, Octokit } from "../types";

export async function createDocsPR({
  octokit,
  owner,
  repo,
  baseBranch,
  prLabel,
  sourcePR,
  updates,
}: CreateDocsPRParams): Promise<string> {
  const { data: baseRef } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });
  const baseSha = baseRef.object.sha;

  const timestamp = Date.now();
  const safePrTitle = sourcePR.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 40)
    .replace(/^-+|-+$/g, "");
  const newBranch = `docpr/pr-${sourcePR.number}-${safePrTitle}-${timestamp}`;

  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${newBranch}`,
    sha: baseSha,
  });
  core.info(`Created branch: ${newBranch}`);

  for (const update of updates) {
    const contentBase64 = Buffer.from(update.content, "utf8").toString(
      "base64"
    );

    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: update.path,
      message: `docs: update ${update.path} for PR ${sourcePR.number} in ${sourcePR.repo}`,
      content: contentBase64,
      branch: newBranch,
      ...(update.originalSha ? { sha: update.originalSha } : {}),
    });
    core.info(`  Committed: ${update.path}`);
  }

  if (prLabel) {
    await ensureLabel({ octokit, owner, repo, label: prLabel });
  }

  const prBody = buildPRBody({ sourcePR, updates });

  const { data: newPR } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: `docs: sync with ${sourcePR.repo}#${sourcePR.number} — ${sourcePR.title}`,
    head: newBranch,
    base: baseBranch,
    body: prBody,
  });

  if (prLabel) {
    try {
      await octokit.rest.issues.addLabels({
        owner,
        repo,
        issue_number: newPR.number,
        labels: [prLabel],
      });
    } catch {
      // Labels are non-critical
    }
  }

  return newPR.html_url;
}

async function ensureLabel({
  octokit,
  owner,
  repo,
  label,
}: {
  octokit: Octokit;
  owner: string;
  repo: string;
  label: string;
}): Promise<void> {
  try {
    await octokit.rest.issues.getLabel({ owner, repo, name: label });
  } catch {
    try {
      await octokit.rest.issues.createLabel({
        owner,
        repo,
        name: label,
        color: "6f42c1",
        description: "Automatically generated documentation update",
      });
    } catch {
      // If we can't create it, skip silently
    }
  }
}

export function buildPRBody({
  sourcePR,
  updates,
}: {
  sourcePR: SourcePR;
  updates: DocUpdate[];
}): string {
  const fileList = updates
    .map((u) => `- \`${u.path}\`${u.reason ? ` — ${u.reason}` : ""}`)
    .join("\n");

  return `## 🤖 docpr

This PR was automatically generated by the **docpr** GitHub Action.

### Source
Triggered by merged PR [${sourcePR.repo}#${sourcePR.number}](${sourcePR.url}):
> **${sourcePR.title}**

### Updated files
${fileList}

### How to review
1. Read the source PR to understand what changed in the codebase.
2. Review each changed doc file below to verify the AI-generated updates are accurate.
3. Edit any sections that need adjustment before merging.

---
*Generated by [docpr](https://github.com/marketplace/actions/docpr). Review carefully before merging.*`;
}
